//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaMedicamento
    {
        public int IIDCITAMEDICAMENTO { get; set; }
        public Nullable<int> IIDCITA { get; set; }
        public Nullable<int> IIDMEDICAMENTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
