//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.CitaMedicamento = new HashSet<CitaMedicamento>();
            this.HistorialCita = new HashSet<HistorialCita>();
        }
    
        public int IIDCITA { get; set; }
        public Nullable<int> IIDUSUARIO { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<decimal> ESTATURA { get; set; }
        public string EXAMENFISICO { get; set; }
        public string EXAMENLABORATORIO { get; set; }
        public string DIAGNOSTICO { get; set; }
        public Nullable<System.DateTime> DFECHACITA { get; set; }
        public Nullable<int> IIDESTADOCITA { get; set; }
        public Nullable<int> IIDSEDE { get; set; }
        public Nullable<decimal> PRECIOATENCION { get; set; }
        public Nullable<decimal> TOTALPAGAR { get; set; }
        public Nullable<System.DateTime> DFECHAINICIOENFERMEDAD { get; set; }
        public Nullable<int> IIDDOCTORASIGNADO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public Nullable<int> IIDPERSONA { get; set; }
        public string DESCRIPCIONENFERMEDAD { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaMedicamento> CitaMedicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCita> HistorialCita { get; set; }
    }
}
