//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int IIDDOCTOR { get; set; }
        public Nullable<int> IIDSEDE { get; set; }
        public Nullable<int> IIDESPECIALIDAD { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<int> IIDPERSONA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
