//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCita
    {
        public int IIDHISTORIALCITA { get; set; }
        public Nullable<int> IIDCITA { get; set; }
        public Nullable<int> IIDESTADO { get; set; }
        public Nullable<int> IIDUSUARIO { get; set; }
        public Nullable<System.DateTime> DFECHA { get; set; }
        public string VOBSERVACION { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
