//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int IIDPACIENTE { get; set; }
        public Nullable<int> IIDTIPOSANGRE { get; set; }
        public string ALERGIAS { get; set; }
        public string ENFERMEDADESCRONICAS { get; set; }
        public string CUADROVACUNAS { get; set; }
        public string ANTECEDENTESQUIRURGICOS { get; set; }
        public Nullable<int> IIDPERSONA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual TipoSangre TipoSangre { get; set; }
    }
}
