//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuarioPaginaBoton
    {
        public int IIDTIPOUSUARIOPAGINABOTON { get; set; }
        public Nullable<int> IIDTIPOUSUARIOPAGINA { get; set; }
        public Nullable<int> IIDBOTON { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Boton Boton { get; set; }
        public virtual TipoUsuarioPagina TipoUsuarioPagina { get; set; }
    }
}
