//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuarioPagina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoUsuarioPagina()
        {
            this.TipoUsuarioPaginaBoton = new HashSet<TipoUsuarioPaginaBoton>();
        }
    
        public int IIDTIPOUSUARIOPAGINA { get; set; }
        public Nullable<int> IIDTIPOUSUARIO { get; set; }
        public Nullable<int> IIDPAGINA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public Nullable<int> IIDVISTA { get; set; }
    
        public virtual Pagina Pagina { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoUsuarioPaginaBoton> TipoUsuarioPaginaBoton { get; set; }
    }
}
